spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candlesticks
    username: postgres
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create